CREATE TABLE `change_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('refund_credits','add_credits','flag_account','note_incident','suspend_user','unsuspend_user','block_ip','other') NOT NULL,
	`status` enum('pending','approved','denied','cancelled','expired') NOT NULL DEFAULT 'pending',
	`priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
	`submittedById` int NOT NULL,
	`submittedByName` varchar(256),
	`targetUserId` int NOT NULL,
	`targetUserName` varchar(256),
	`title` varchar(512) NOT NULL,
	`description` text NOT NULL,
	`evidenceSummary` text,
	`relatedAuditLogId` int,
	`creditAmount` int,
	`creditReason` varchar(512),
	`ipAddress` varchar(45),
	`reviewedById` int,
	`reviewedByName` varchar(256),
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `change_requests_id` PRIMARY KEY(`id`)
);
