-- The refinement TREE, made explicit — fork-safe segment sets (fable-091).
--
-- The founder's semantics: "if you go back to a previous edit, the layers are
-- only what that currently selected image holds — you can fork-edit from any
-- previous edit." Refinement history is therefore a tree, and the set of kept
-- pieces a render carries has one answer PER BRANCH.
--
-- Until now the only ancestry in a variant row was `instructions`, the
-- accumulated recipe, and the segment store answered "what does this face
-- keep" from a single global live-list per candidate. A fork from B inherited
-- D's glasses and lost the facets D had superseded. One flag cannot hold one
-- answer per branch.
--
-- PURELY ADDITIVE and NULLABLE. NULL means "made from the candidate itself",
-- which is what every existing row is: before this column there was no
-- version-jumping recorded, so reading every historical variant as the first
-- edit of its own branch is the only honest backfill, and it is exactly what
-- NULL already means. Nothing reads this column until the segment store is
-- armed, so an application version in flight cannot be confused by it.
--
-- This changes NOTHING about base-anchoring. Every variant is still
-- `edit(the ORIGINAL, instructions 1..N)`; this records which face the user was
-- LOOKING AT when they asked, never which image was fed to the painter.
ALTER TABLE `casting_candidate_variants` ADD `parentVariantId` int;
--> statement-breakpoint
-- The ancestry walk runs per render, scoped to one candidate, so the index it
-- wants is the one that answers "who are this variant's children" cheaply.
CREATE INDEX `idx_casting_variants_parent` ON `casting_candidate_variants` (`parentVariantId`);
