-- THE KIND-PROPERTY STORE (`OPEN_KIND_PROPERTIES_DESIGN.md` §5, ordered
-- fable-872 §2 + fable-868 §4 as ONE design, opened for build by fable-895 §4).
--
-- One row is: **a fact about a KIND that the catalogue would have held, which
-- nobody has catalogued.** Two of them, answered once per noun ever:
--
--   locality       can one crop hold every instance — `single`, `coLocated`
--                  (fangs), `distributed` (wings)
--   anchorRegion   where on a body the thing is anchored — `belowWaist` for a
--                  tail, `hands` for nails
--
-- ============================================================================
-- WHY THE SECOND PROPERTY IS A PLACE AND NOT A BOOLEAN (ruled fable-897 §3)
-- ============================================================================
--
-- It was designed as *"does this kind extend — anchored outside the frame, does
-- it present inside it?"*, a boolean. **That question contains a framing, and
-- this table holds one row per kind.** The product has EIGHT framings: the refine
-- road's waist-up master, and a signed Cast's close-up, three head-and-shoulders
-- views and three head-to-feet views. So *does a tail present in the frame* is NO
-- on the road that paints it and YES on the full-length views, and one boolean
-- would force one of those answers onto the other seven — surfacing, of all
-- places, in the founder's own obligation court.
--
-- So the model answers the KIND (where is this thing anchored) and the CODE
-- answers the FRAME (`bodyAnchorRegions.ts`, a total table over every framing, so
-- a new view does not compile until somebody decides what it shows). Same one
-- call per kind, one fewer model opinion in the product, and a control that can
-- be answered wrong in an obvious way — `nails → hands`, never `nails → head`.
--
-- PURELY ADDITIVE. One new table. No column of any existing table changes, and
-- **nothing reads or writes it in this commit** — the reader is its own step and
-- the mint gate is the step after that. The migration lands first anyway,
-- because a new table is in every INSERT the moment its writer ships and there
-- is no dark landing for one; this program has the scar that named the rule.
--
-- ============================================================================
-- WHY IT IS A TABLE AND NOT A COLUMN ON `casting_open_lane_demand`
-- ============================================================================
--
-- The demand table is per-ASK and these are per-KIND. A property written onto
-- every ask row is the same fact stored N times waiting to disagree with itself
-- — the parallel-copy violation (working law 4) with a model's answer inside it.
-- And it would put a *judgement about a word* into the one table whose column
-- list is a privacy boundary.
--
-- The privacy shape here is different and simpler: **a row of this table is
-- about the ENGLISH LANGUAGE, not about a person.** `wings are a pair` is not a
-- fact about whoever asked for wings. There is no userId to leave out, no
-- candidate, no image key, and no timestamp correlation worth naming, because
-- one row is written the first time a noun is ever seen and never again.
--
-- ============================================================================
-- ONE ROW PER KIND, AND THE UNIQUE KEY IS ON `kind` ALONE
-- ============================================================================
--
-- The tempting key is (kind, promptVersion), so a re-ask under a better prompt
-- can land beside the old answer. That is the wrong shape and the reason is the
-- one this campaign keeps paying for: two rows for one kind is two answers to
-- one question, and every reader then needs a rule for picking — a rule that can
-- differ between readers, which is how a property that must be stable per kind
-- starts wobbling per caller.
--
-- So the key is the kind, the answering model and prompt travel ON the row as
-- provenance, and a re-ask under a new prompt is an UPDATE by a build that has
-- decided to re-ask. Declared here so that build finds this paragraph rather
-- than a second unique index.
--
-- ============================================================================
-- BOTH PROPERTIES ARE NOT NULL, AND THE ABSENCE OF A ROW IS THE THIRD STATE
-- ============================================================================
--
-- A reader that declined has produced no fact, so it writes NO ROW. It does not
-- write a row with nulls in it. Two meanings of "we do not know" one field apart
-- is the `whenAbsent` defect from the bald row, and here it would be worse: a
-- nullable `paired` read by a gate that treats null as false would mint a crop
-- of one wing under the name of two — precisely the thing fable-872 §2 forbade.
--
-- `anchorRegion` is an ENUM of the eight places `bodyAnchorRegions.ts` lists, so
-- a region nobody designed cannot be stored even if a reader invents one. The
-- ceremony reads the enum's members back and compares them against that list,
-- because a hand-written DDL beside a TypeScript constant is the parallel copy
-- that drifts (working law 4) — and here the drift would be silent until a
-- framing derivation asked about a place the table had never heard of.
--
-- The cost of that choice, stated: while the text transport is down, every ask
-- for a kind with no row re-buys the read and gets nothing. That is bounded by
-- the render itself needing the same transport, and it is cheaper than a
-- persisted "unknown" that a later reader mistakes for an answer.
--
-- ============================================================================
-- RETENTION
-- ============================================================================
--
-- Nothing here is personal data and nothing points at an object in storage, so
-- this table is NOT swept with a candidate and must not be — the point of paying
-- for a per-kind read once is that it is answered once, forever, for everybody.
CREATE TABLE `casting_open_kind_properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	-- The NORMALIZED key the open lane minted — a single lowercase token. 64 to
	-- match `kind` on the demand table and `noun` on the reference library, which
	-- are the same word in the same ontology.
	`kind` varchar(64) NOT NULL,
	-- P1. WHERE the instances of this kind sit relative to each other. NOT the
	-- question of whether THIS render produced two of them, which is a fact about
	-- a frame (D1) and lives with the delivery.
	--
	-- It was `paired boolean` until the founder's fangs ruling (fable-951): *"fangs
	-- are apart of teeth as a whole though right? no need for a left and right
	-- fang?"*, with the instruction that it *"must not be just a fang upgrade it
	-- must apply to anything of the sort."* What decides whether a crop may carry a
	-- kind is not how many instances there are — it is whether ONE CROP CAN HOLD
	-- THEM. `single` and `coLocated` may be cropped; `distributed` is counting-
	-- gated, because a whole-frame read of two things on opposite sides returns one
	-- of them wearing the plural's name.
	--
	-- AMENDED IN PLACE rather than followed by an ALTER, under the same two facts
	-- as when this file was written: the table is dev-only and PRODUCTION HAS NEVER
	-- TAKEN 0033. The dev database is re-taken by dropping the table and re-running
	-- this file, and existing rows are re-read under the new vocabulary rather than
	-- mapped from the old one — a boolean cannot say which side of the new split a
	-- kind falls on, and inventing that answer is the mirror of the fold this
	-- ruling removed.
	`locality` enum('single','coLocated','distributed') NOT NULL,
	-- P2. WHERE on a body the thing is anchored — the per-kind half. Whether that
	-- place is inside a given framing is derived in `bodyAnchorRegions.ts` and is
	-- deliberately not stored, because the answer differs across the product's
	-- eight framings and a row cannot hold eight answers.
	`anchorRegion` enum('head','neck','torso','arms','hands','belowWaist','feet','wholeBody') NOT NULL,
	-- Provenance, so a later reading is a delta rather than an anecdote: WHICH
	-- model answered and WHICH prompt asked. A property whose answer changed
	-- because the question changed is otherwise indistinguishable from a property
	-- that was never stable.
	`model` varchar(128) NOT NULL,
	`promptVersion` varchar(32) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `casting_open_kind_properties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
-- The bound: one row per kind, ever. The read is keyed on exactly this.
CREATE UNIQUE INDEX `uq_casting_open_kind_properties_kind` ON `casting_open_kind_properties` (`kind`);
