-- WHICH CREDITS EXPIRE, AND WHEN — three additive columns (#2185, his rulings
-- 2026-10-10, verbatim: "Referral credits (proposed) Never expire, same as
-- top-ups.", "promo and signup bonuses after 90 days? Expire after 90 days.",
-- and then, for the starting credits: "starting credits are just a default
-- every account starts with lets make them never expire to simplify things.").
--
-- ============================================================================
-- THE RULE THEY CARRY
-- ============================================================================
--
--   Top-ups            never expire (`purchasedBalance`, unchanged)
--   Starting credits   never expire                      -> keptBalance
--   Referral credits   never expire                      -> keptBalance
--   Staff goodwill     never expires                     -> keptBalance
--   Promo bonuses      expire 90 days after the grant    -> promoBalance,
--                                                          promoCreditsExpireAt
--   Plan credits       unchanged: what is left of the balance
--
-- Each `…Balance` is an upper bound read the way `purchasedBalance` is: the
-- balance spends plan -> promo -> kept -> purchased, so a bucket's remaining
-- credits are the lesser of its bound and what the later buckets leave over.
-- Nothing is written on the spend path.
--
-- ============================================================================
-- DEFAULTS — AND WHAT THAT MEANS FOR THE ROWS THAT EXIST
-- ============================================================================
--
-- Every existing row gets 0 and NULL. That reads exactly as before this
-- migration: those credits stay in the plan's part. No row is rewritten — his
-- answer on the backfill, 2026-10-10: "leave existing accounts alone".
--
-- PURELY ADDITIVE. Three columns, no index, no existing column changes.
ALTER TABLE `points` ADD COLUMN `keptBalance` int NOT NULL DEFAULT 0;
--> statement-breakpoint
ALTER TABLE `points` ADD COLUMN `promoBalance` int NOT NULL DEFAULT 0;
--> statement-breakpoint
ALTER TABLE `points` ADD COLUMN `promoCreditsExpireAt` timestamp NULL;
