import { useMemo } from "react";
import type { CastingBindings } from "./castingBindings";

/**
 * useCastingViewGeneration — post-headshot "next step" affordance.
 *
 * Stage-lock RETIRED (D-46, the unification): the old head→lock→body→lock→side
 * ladder and its `StageLockModal` are gone. Views are no longer generated by
 * this hook (the ungated `generation.fullBody`/`multiView` endpoints were
 * removed); every view now flows through the mint gate (`mintPackage`), opened
 * from the view strip's package ghosts. What remains here is a single forward
 * affordance: once a full body exists, offer Export.
 */
interface UseCastingViewGenerationParams {
  bindings: CastingBindings;
}

export function useCastingViewGeneration({ bindings }: UseCastingViewGenerationParams) {
  const { genState, currentAssets, setShowExportModal } = bindings;

  // The only remaining "next step": export the character pack. View
  // generation is not a staged ladder anymore — it's the mint gate.
  const nextStage = useMemo(() => {
    if (currentAssets.length === 0 || genState.isGenerating) return null;
    if (!currentAssets.some((a) => a.viewType === "frontFull")) return null;
    return {
      label: "Export Character Pack",
      action: () => setShowExportModal(true),
      step: 4,
      total: 3,
    };
  }, [currentAssets, genState.isGenerating, setShowExportModal]);

  return { nextStage };
}
