/**
 * mintIntegrity — §14's three SEPARATE mint validity checks (ratified R8,
 * Batch C). Never one vague "headshot out of sync" state:
 *
 *  1. IDENTITY-ANCHOR validity — a filled authoritative anchor (shared §7
 *     selector), known authority, current revision (or the accepted legacy
 *     genesis/fingerprint case), neither stale nor failed.
 *  2. DISPLAY-HEADSHOT validity — a same-revision `display` headshot sitting
 *     above an older authoritative anchor legally PASSES (that divergence
 *     alone never blocks mint); an earlier- or unknown-revision displayed
 *     headshot refuses with its own copy.
 *  3. TIER-VIEW validity — every selected-tier view that exists must be
 *     fresh (not stale — pinned or unpinned), successful, and belong to the
 *     current revision.
 *
 * Pure — consumed by plan (dialog prediction, per check, with its own copy)
 * and execute (refusal before deduction).
 */
import { VIEW_ANGLE_LABELS, type CanonicalViewAngle } from "../../../shared/boardTypes";
import {
  type AnchorAssetRow,
  assetRevisionMembership,
  isStaleAsset,
  selectDisplayedHeadshot,
  selectIdentityAnchor,
} from "./anchorSelector";
import { REFUSAL_COPY } from "./refusalCopy";

export interface MintCheck {
  ok: boolean;
  message?: string;
}

export interface TierViewCheck {
  angle: CanonicalViewAngle;
  label: string;
  /** Missing slots are generated by the mint itself — not a pre-refusal. */
  present: boolean;
  ok: boolean;
  reason?: "stale" | "pinned_stale" | "failed" | "cross_revision" | "unknown_authority";
  message?: string;
}

export interface MintIntegrity {
  anchor: MintCheck;
  displayHeadshot: MintCheck;
  tierViews: TierViewCheck[];
  ok: boolean;
}

export interface MintIntegrityModel {
  status?: string | null;
  identityRevisionId?: string | null;
}

function isFailedMarkerRow(assets: AnchorAssetRow[], angle: CanonicalViewAngle): boolean {
  // Failed only when nothing is filled AND the newest attempt is a marker
  const forAngle = assets.filter((a) => a.viewType === angle);
  const filled = forAngle.find((a) => a.storageUrl);
  if (filled) return false;
  const newest = forAngle[0];
  const status = newest?.status as { state?: string } | undefined;
  return status?.state === "failed";
}

export function computeMintIntegrity(
  model: MintIntegrityModel,
  assets: AnchorAssetRow[],
  tierAngles: readonly CanonicalViewAngle[],
  currentIdentityText: string,
): MintIntegrity {
  const genesis = !model.identityRevisionId;

  // ── Check 1: identity-anchor validity ─────────────────────────────────────
  const anchorRow = selectIdentityAnchor(assets);
  let anchor: MintCheck = { ok: true };
  if (!anchorRow) {
    anchor = { ok: false, message: REFUSAL_COPY.mintAnchorInvalid };
  } else if (isStaleAsset(anchorRow)) {
    anchor = { ok: false, message: REFUSAL_COPY.mintAnchorInvalid };
  } else {
    const membership = assetRevisionMembership(anchorRow, model, currentIdentityText);
    const anchorOk =
      membership === "current" ||
      membership === "legacy-match" ||
      // The accepted legacy genesis case (§14/§7.4): a pre-Batch-C anchor on
      // a model that has never taken an identity-authorized anchor change.
      (genesis && membership === "unknown");
    if (!anchorOk) anchor = { ok: false, message: REFUSAL_COPY.mintAnchorInvalid };
  }

  // ── Check 2: display-headshot validity ────────────────────────────────────
  const displayed = selectDisplayedHeadshot(assets);
  let displayHeadshot: MintCheck = { ok: true };
  if (displayed && anchorRow && displayed.id !== anchorRow.id) {
    const membership = assetRevisionMembership(displayed, model, currentIdentityText);
    if (!(membership === "current" || membership === "legacy-match")) {
      displayHeadshot = { ok: false, message: REFUSAL_COPY.mintDisplayHeadshotInvalid };
    } else if (isStaleAsset(displayed)) {
      displayHeadshot = { ok: false, message: REFUSAL_COPY.mintDisplayHeadshotInvalid };
    }
  }

  // ── Check 3: tier-view validity ───────────────────────────────────────────
  const tierViews: TierViewCheck[] = tierAngles
    .filter((angle) => angle !== "frontClose")
    .map((angle) => {
      const label = VIEW_ANGLE_LABELS[angle];
      const filled = assets.find((a) => a.viewType === angle && a.storageUrl);
      if (!filled) {
        if (isFailedMarkerRow(assets, angle)) {
          return { angle, label, present: true, ok: false, reason: "failed" as const, message: REFUSAL_COPY.mintTierViewFailed(label) };
        }
        // Missing slots are generated by the mint itself
        return { angle, label, present: false, ok: true };
      }
      if (isStaleAsset(filled)) {
        const pinned = !!filled.pinned;
        return {
          angle, label, present: true, ok: false,
          reason: (pinned ? "pinned_stale" : "stale") as "pinned_stale" | "stale",
          message: pinned ? REFUSAL_COPY.pinnedStale(label) : REFUSAL_COPY.mintTierViewStale(label),
        };
      }
      const membership = assetRevisionMembership(filled, model, currentIdentityText);
      if (membership === "mismatch") {
        return { angle, label, present: true, ok: false, reason: "cross_revision" as const, message: REFUSAL_COPY.mintTierViewCrossRevision(label) };
      }
      if (membership === "unknown") {
        // Uncertain provenance refuses rather than guessing (§7.4) — legacy
        // iterate-created rows carry none; a refresh stamps the current
        // revision and resolves it.
        return { angle, label, present: true, ok: false, reason: "unknown_authority" as const, message: REFUSAL_COPY.mintTierViewStale(label) };
      }
      return { angle, label, present: true, ok: true };
    });

  return {
    anchor,
    displayHeadshot,
    tierViews,
    ok: anchor.ok && displayHeadshot.ok && tierViews.every((v) => v.ok),
  };
}
