/**
 * A SIGNED CAST'S TATTOOS RIDE INTO EVERY VIEW AS PICTURES — the view-reference
 * lane (FOUNDER RULING, his words at fable-987 §3: *"tattoo reference will need
 * to be supplied to each view generated otherwise it wont know what the tattoo
 * is"*).
 *
 * # What was wrong before this
 *
 * A package view was rendered from the anchor alone. The anchor is a chest-up
 * photograph of her face; a tattoo on her upper arm is outside it or barely in
 * it, so five views were generated by an engine that had never been shown the
 * artwork. Whatever it drew there it invented.
 *
 * # THE PLATE IS THE ONLY INK ARTIFACT AN ENGINE IS EVER SHOWN (D-138)
 *
 * What rides is the PLATE — the design already drawn onto a blank mannequin
 * form — never the customer's uploaded photograph. That is the real-person
 * fence met by construction rather than by a filter, and it is why this module
 * takes plates and has no way to name an upload.
 *
 * # AND THE SENTENCE NAMES THE GRAPHIC, NEVER THE FORM
 *
 * The plate is a picture of a grey mannequin limb wearing a tattoo. Handed to
 * an engine with no instruction, the obvious reading is *make the photograph
 * look like this* — grey skin, blank background, no person. So the clause says
 * exactly one thing: copy the ARTWORK, at this surface, and nothing else from
 * the picture. It is the same discipline the plate prompt itself runs on, one
 * station along, and it is the fence held from the inside (fable-876 §2: the
 * sheet references the graphic and never re-describes the person).
 *
 * # RIDES EVERY VIEW, INCLUDING THE ONES THAT CANNOT SHOW IT
 *
 * His ruling, and the reason is asymmetric rather than aesthetic. A view that
 * cannot show the surface simply does not show it — the clause says where the
 * tattoo lives and a back view of her shoulders is not that place. Withholding
 * the reference has the quiet failure instead: a three-quarter frame that
 * happens to catch her upper arm, rendered by an engine holding no picture of
 * the tattoo, comes back with bare skin, and the customer's tattoo has vanished
 * from one frame of six with nothing in the record saying why.
 *
 * The opposite risk — an engine putting a chest tattoo on a back view because
 * it was handed the picture — is real, and it is not argued about here: the
 * conformance control buys the answer before this rides anything paid, with a
 * must-SHOW arm as well as a must-not-show one (fable-1004 §2). If bleed shows,
 * the fallback is a per-view visibility table, which is a table rather than a
 * guess.
 */
import { inkPlacementEntry, type InkPlacement } from "../../shared/inkPlacementVocabulary";
import { imageHalfClause } from "./sidePhrasing";
import type { InkSide } from "../../shared/inkReleasedPlacements";

/**
 * One plate as a view render sees it: the artwork's bytes and the surface they
 * belong on.
 *
 * The design's own public id travels so an outcome can NAME the tattoo that did
 * or did not ride — a reference that silently failed to ride is the same defect
 * as a control nobody invokes.
 */
export type CarriedInkPlate = {
  readonly designPublicId: string;
  readonly placement: InkPlacement;
  readonly side: InkSide;
  readonly bytes: Buffer;
  readonly contentType: string;
};

/**
 * WHERE THIS TATTOO LIVES, in the word the reading measured.
 *
 * `readerWord` rather than the customer noun, for the reason `inkPlatePrompt`
 * gives at the same fork: the customer's copy carries "her", and the vocabulary
 * measured which word actually cuts this surface — "upper chest" found bare
 * skin that `collarbone`, `clavicle` and `decolletage` all missed. Derived, so a
 * caller cannot supply a word the vocabulary disagrees with.
 */
export function inkPlacementPhrase(input: { placement: InkPlacement; side: InkSide }): string {
  const surface = inkPlacementEntry(input.placement).readerWord;
  if (input.side === "centre") return `her ${surface}`;
  /*
    AND WHICH HALF OF THE PICTURE THAT IS — unconditionally on this lane
    (ordered fable-1006 §3, bought by the court's own miss).

    **THE CLAUSE DOES NOT DECIDE THE SIDE ON THIS LANE**, and that is measured
    rather than suspected. The commit that added it read as a repair; an hour
    later its own diagnostic overturned that reading. The same plate bytes,
    described once as her left and once as her right — five renders, three
    different claims, two of them carrying THIS clause pointing the opposite way
    — put the tattoo on the image's LEFT arm every time. The four-in-twelve
    measurement behind the sentence is the EYE lane's
    (`V4_SIDE_INFERENCE_COURT.md`) and it stands on its own road; it did not
    transfer here.

    **WHAT DECIDES HERE IS THE PICTURE.** The mirror court asked the question
    that cannot be answered wrong: the same claim, the same everything, the
    plate bytes FLIPPED. The ink follows the plate's own half of the frame —
    3/3 mirrored onto the image's right, 2/2 as-is onto the image's left in the
    same interleaved sitting, against a 7/7 as-is baseline. It is this
    program's carrier law arriving on one more lane: a crop holds the region it
    PICTURES, and a plate holds the side it pictures.

    So a per-side promise here is kept by GEOMETRY rather than by prose — the
    blank a design is plated onto must face the side the design declares, which
    is the founder's own right-facing/left-facing template pair. The fix is
    drawn and queued on the template commit's checklist, §7.10 item 4 of
    `V3B_INK_AND_MARKS_DESIGN_NOTE.md`. **Until those blanks land, an upper-arm
    tattoo can ride a package view on the wrong arm.** Nothing paid is exposed:
    `CASTING_INK_STUDIO_SCOPE` is absent in production, so no design row exists,
    so no plate exists, so this clause is never written there.

    The clause stays — it is the right sentence, it costs nothing per render,
    and it is what the other lane measured. It is unconditional here because the
    view clause is house prose on a new road with no installed behaviour to
    protect — `CASTING_SIDE_PHRASING_SCOPE` governs the REPAINT recipe, which is
    a different lane with a different history.

    Through the one owner rather than spelled here: a second copy of this phrase
    would drift at exactly the point it exists to hold still.
  */
  return `her ${input.side} ${surface}${imageHalfClause(input.side)}`;
}

/**
 * MAY A DESIGN AT THIS SURFACE RIDE A PACKAGE VIEW AT ALL — the interim ordered
 * fable-1006 §2, and the court is what bought it.
 *
 * The upper chest is bare **on a scoop neckline only** — the placement
 * vocabulary has said so since the day sixteen production masters were measured
 * — and the package wardrobe is a FIXED crew neck, unchanged across every view.
 * Those two promises cannot both hold in one frame, and the engine demonstrated
 * it by breaking each in turn: told to put the artwork on her upper chest it
 * printed the design on the shirt; told that ink goes on skin and never on
 * cloth, it rewrote the crew neck into a scoop and drew it on the skin beneath.
 *
 * **Both outcomes fail the package's own wardrobe check, and a failed view is a
 * refunded slice** — so an upper-chest design carries no plate into a package
 * view and says so on the same disposition surface as every other way a design
 * can fail to ride.
 *
 * # HE HAS NOW RULED THE WARDROBE, AND IT IS NOT WHAT LIFTS THIS
 *
 * The interim above read *"until he rules on the wardrobe itself"*, and he
 * ruled on 2026-08-19 (fable-1081 §2–§3): **the crew neck stays a crew neck**,
 * the wardrobe is never altered for a tattoo, and a covered design shows
 * whatever the collar leaves bare and nothing more. That answer closes the
 * question this interim was waiting on WITHOUT lifting the interim, which is
 * the distinction worth writing down rather than remembering — a ruling that
 * settles a question is not automatically a ruling that opens a door.
 *
 * **What lifts it is the crop road** (fable-1081 §3), where a chest design
 * rides as reference plus words like every other feature instead of as a plate
 * the engine must reconcile with a neckline. Until then the two failures above
 * are still the only two outcomes available, and both still cost a slice.
 *
 * TOTAL over the vocabulary, like `TEMPLATE_FOR` and the anchor regions and for
 * the same reason: a default would decide a new surface's visibility by
 * whichever value was listed first, and nothing would say so.
 */
const RIDES_PACKAGE_VIEWS: Readonly<Record<InkPlacement, boolean>> = Object.freeze({
  /* The crew tee's neckline sits below it; every measured master shows it bare. */
  neck: true,
  /* A short sleeve leaves it bare, and the court's passing arm is exactly this
     case: ink on skin, below the sleeve, the garment untouched. */
  upperArm: true,
  /* Covered by the package's own crew neck, which STAYS a crew neck (his
     ruling, fable-1081 §2). The crop road is what lifts this, not the ruling. */
  upperChest: false,
});

export function placementRidesPackageViews(placement: InkPlacement): boolean {
  return RIDES_PACKAGE_VIEWS[placement];
}

/**
 * The clause that rides beside the anchor, one sentence group per plate.
 *
 * `firstOrdinal` is the position of the FIRST plate in the request's reference
 * array — the anchor is reference 1, so plates start at 2. It is passed rather
 * than assumed, because the ordinal a sentence quotes and the slot a reference
 * actually occupies drifting apart is a prompt that points at the wrong picture.
 *
 * Empty string when nothing rides: a Cast with no plated tattoo must produce the
 * prompt it produces today, byte for byte, or every signed Cast in the product
 * has quietly changed.
 */
export function inkViewReferenceClause(input: {
  plates: readonly CarriedInkPlate[];
  firstOrdinal: number;
}): string {
  if (input.plates.length === 0) return "";
  const lines: string[] = [
    "HER TATTOOS — each of the following reference pictures shows one tattoo she already has, "
    + "drawn on a plain grey mannequin form so the artwork can be seen clearly.",
  ];
  input.plates.forEach((plate, index) => {
    const where = inkPlacementPhrase(plate);
    lines.push(
      `Reference ${input.firstOrdinal + index} is the tattoo at ${where}. Copy the ARTWORK from it — `
      + "its shapes, its line weight, its shading and any lettering exactly as they appear — onto her "
      + `own skin at ${where}, following the form of her body so it sits as ink on skin rather than as `
      + "a flat sticker. Do not restyle it, do not simplify it, and do not add to it.",
    );
  });
  lines.push(
    "The mannequin form in those pictures is NOT part of the tattoo: its grey colour, its shape, its "
    + "background and its lighting must not appear anywhere in the photograph, and it must never "
    + "change her skin, her build or her pose.",
  );
  /*
    INK IS ON SKIN, AND A COVERED SURFACE MEANS ABSENT — the first conformance
    court's own finding (2026-08-19), and it cost a render to learn.

    Handed an upper-chest plate and a `frontFull` view whose wardrobe is a
    crew-neck tee, the engine printed the design ON THE SHIRT: the artwork
    reproduced faithfully, in the wrong material. It was the only way to satisfy
    what it had been told — the upper chest is COVERED on a crew neck, which the
    placement vocabulary states in its own table, so there was no skin in that
    frame to put it on.

    And it is a money defect rather than a cosmetic one: the package's wardrobe
    check calls printed text or a logo on the garment a failure WHEREVER it
    appears, so that view would have been refused and its slice refunded. An
    upper-chest tattoo would have cost a slice of every Sign it rode.

    # AND WHAT THE COVERED CASE LOOKS LIKE IS NOW HIS RULING, NOT A SIDE EFFECT

    Founder, 2026-08-19 (relayed fable-1081), on the same question that closed
    the scoop-neck card:

    > *"tattos can still ride they may just not be visible fully yet so if you
    > had a chest tatto reference with neck continuation you might see it poking
    > out the top of the shirt but thats the extent for now"*

    So clothing COVERS ink rather than deleting it, and the sentence below says
    so in those terms. The earlier wording — *"the tattoo is simply not visible
    in that view"* — was true of a design wholly under a collar and WRONG of the
    one he described: a chest piece that runs up the neck has a part on bare
    skin, and that part shows. The wardrobe is never altered to reveal more of
    it, and no view is added to; a poke above the collar is the whole of what a
    covered design gets, and that is the promise rather than the compromise.
  */
  lines.push(
    "It is ink on her skin — never printed, embroidered or otherwise placed on her clothing, and "
    + "never added to a garment as a graphic. Clothing covers ink rather than removing it: where a "
    + "tattoo runs under a garment, the part of it on bare skin appears exactly as it is and the "
    + "covered part simply does not show. Never change, move or open a garment to reveal more of a "
    + "tattoo — the clothing in a view is what it is, and the tattoo shows only where skin shows.",
  );
  lines.push(
    "Each tattoo sits where it is named and nowhere else — do not move one to a nearby part of the "
    + "body, do not mirror it to her other side, and do not draw a second copy of it. Where a view "
    + "does not show the surface a tattoo is on, that tattoo simply does not appear in that view.",
  );
  return lines.join("\n");
}
