/**
 * A SIGNED CAST'S TATTOOS RIDE INTO EVERY VIEW AS PICTURES — the view-reference
 * lane (FOUNDER RULING, his words at fable-987 §3: *"tattoo reference will need
 * to be supplied to each view generated otherwise it wont know what the tattoo
 * is"*).
 *
 * # What was wrong before this
 *
 * A package view was rendered from the anchor alone. The anchor is a chest-up
 * photograph of her face; a tattoo on her upper arm is outside it or barely in
 * it, so five views were generated by an engine that had never been shown the
 * artwork. Whatever it drew there it invented.
 *
 * # THE CUSTOMER'S UPLOADED PHOTOGRAPH IS NEVER SHOWN AN ENGINE (D-138)
 *
 * ⚠ **THIS SECTION READ *"THE PLATE IS THE ONLY INK ARTIFACT AN ENGINE IS EVER
 * SHOWN"* UNTIL 2026-08-21, AND THERE ARE NOW TWO LANES HERE.** The sentence was
 * true of a module that could only take plates; it stopped being true the hour a
 * second lane landed, and a header describing a room that has changed is this
 * repo's own named failure rather than a stale nicety.
 *
 * What the fence actually forbids is **her uploaded photograph** — someone's
 * real body, given to us for a design. Two things may ride, and neither is that:
 *
 *   PLATE            the design drawn onto a blank mannequin form. Parked
 *                    (`MANNEQUIN_ROAD_DEFERRED`), so it has never ridden
 *   DELIVERED CROP   the tattoo cut out of a frame THIS PRODUCT rendered and
 *                    she paid for — our own pixels, of a person who does not
 *                    exist outside them
 *
 * **The scope question that separates them was recorded and is now answered.**
 * It was the fourth item of the mannequin sitting (fable-1202 §2 / 1222): *if
 * D-138's fence names UPLOADS, then a tattoo she only ever DESCRIBED IN WORDS
 * could ride into her package views as a picture, with no mannequin anywhere in
 * the road.* Closed by the founder's own two sentences, both 2026-08-21 and both
 * verbatim on file — *"word invented tattoos are fine as long as the engine can
 * find and crop them to be references moving foward into other edits"* and
 * *"crop and reference any tattos it can find and see - this would intrun carry
 * into the signing angles"* — read as the ruling by fable-1297 §2, which named
 * the revert in the same breath. The destination is his own word for it.
 *
 * # AND THE SENTENCE NAMES THE GRAPHIC, NEVER THE FORM
 *
 * The plate is a picture of a grey mannequin limb wearing a tattoo. Handed to
 * an engine with no instruction, the obvious reading is *make the photograph
 * look like this* — grey skin, blank background, no person. So the clause says
 * exactly one thing: copy the ARTWORK, at this surface, and nothing else from
 * the picture. It is the same discipline the plate prompt itself runs on, one
 * station along, and it is the fence held from the inside (fable-876 §2: the
 * sheet references the graphic and never re-describes the person).
 *
 * # RIDES EVERY VIEW, INCLUDING THE ONES THAT CANNOT SHOW IT
 *
 * His ruling, and the reason is asymmetric rather than aesthetic. A view that
 * cannot show the surface simply does not show it — the clause says where the
 * tattoo lives and a back view of her shoulders is not that place. Withholding
 * the reference has the quiet failure instead: a three-quarter frame that
 * happens to catch her upper arm, rendered by an engine holding no picture of
 * the tattoo, comes back with bare skin, and the customer's tattoo has vanished
 * from one frame of five with nothing in the record saying why.
 *
 * The opposite risk — an engine putting a chest tattoo on a back view because
 * it was handed the picture — is real, and it is not argued about here: the
 * conformance control buys the answer before this rides anything paid, with a
 * must-SHOW arm as well as a must-not-show one (fable-1004 §2). If bleed shows,
 * the fallback is a per-view visibility table, which is a table rather than a
 * guess.
 */
import { inkPlacementEntry, type InkPlacement } from "../../shared/inkPlacementVocabulary";
import { coverageOfWardrobeLine, type SurfaceCoverage } from "./inkSurfaceCoverage";
import { INK_NOT_ON_CLOTHING, inkDeliveredCarrySentence } from "./inkRealism";
import type { CastPronouns } from "./castPronouns";
import { imageHalfClause } from "./sidePhrasing";
import type { InkSide } from "../../shared/inkReleasedPlacements";

/**
 * One plate as a view render sees it: the artwork's bytes and the surface they
 * belong on.
 *
 * The design's own public id travels so an outcome can NAME the tattoo that did
 * or did not ride — a reference that silently failed to ride is the same defect
 * as a control nobody invokes.
 */
export type CarriedInkPlate = {
  readonly designPublicId: string;
  readonly placement: InkPlacement;
  readonly side: InkSide;
  readonly bytes: Buffer;
  readonly contentType: string;
};

/**
 * WHERE THIS TATTOO LIVES, in the word the reading measured.
 *
 * `readerWord` rather than the customer noun, for the reason `inkPlatePrompt`
 * gives at the same fork: the customer's copy carries "her", and the vocabulary
 * measured which word actually cuts this surface — "upper chest" found bare
 * skin that `collarbone`, `clavicle` and `decolletage` all missed. Derived, so a
 * caller cannot supply a word the vocabulary disagrees with.
 */
export function inkPlacementPhrase(input: {
  placement: InkPlacement;
  side: InkSide;
  /**
   * WHOSE surface it is — `his`, `her`, `their`.
   *
   * A parameter rather than a literal because there are two lanes on this
   * function now and only one of them can spell it. The plate lane's clause
   * hard-codes "her" throughout (a defect named in this module's own header),
   * so it passes that same word here rather than pretending to a pronoun its
   * surrounding sentences do not have; the delivered-crop lane passes the
   * CAST's, which is `inkDeliveredCarrySentence`'s rule and this room's oldest
   * scar.
   *
   * What must NOT be duplicated is everything below this line — which half of
   * the picture a side is, and the one owner it comes from.
   */
  possessive: string;
}): string {
  const surface = inkPlacementEntry(input.placement).readerWord;
  if (input.side === "centre") return `${input.possessive} ${surface}`;
  /*
    AND WHICH HALF OF THE PICTURE THAT IS — unconditionally on this lane
    (ordered fable-1006 §3, bought by the court's own miss).

    **THE CLAUSE DOES NOT DECIDE THE SIDE ON THIS LANE**, and that is measured
    rather than suspected. The commit that added it read as a repair; an hour
    later its own diagnostic overturned that reading. The same plate bytes,
    described once as her left and once as her right — five renders, three
    different claims, two of them carrying THIS clause pointing the opposite way
    — put the tattoo on the image's LEFT arm every time. The four-in-twelve
    measurement behind the sentence is the EYE lane's
    (`V4_SIDE_INFERENCE_COURT.md`) and it stands on its own road; it did not
    transfer here.

    **WHAT DECIDES HERE IS THE PICTURE.** The mirror court asked the question
    that cannot be answered wrong: the same claim, the same everything, the
    plate bytes FLIPPED. The ink follows the plate's own half of the frame —
    3/3 mirrored onto the image's right, 2/2 as-is onto the image's left in the
    same interleaved sitting, against a 7/7 as-is baseline. It is this
    program's carrier law arriving on one more lane: a crop holds the region it
    PICTURES, and a plate holds the side it pictures.

    So a per-side promise here is kept by GEOMETRY rather than by prose — the
    blank a design is plated onto must face the side the design declares, which
    is the founder's own right-facing/left-facing template pair. The fix is
    drawn and queued on the template commit's checklist, §7.10 item 4 of
    `V3B_INK_AND_MARKS_DESIGN_NOTE.md`. **Until those blanks land, an upper-arm
    tattoo can ride a package view on the wrong arm.** Nothing paid is exposed
    — and ⚠ **the proof is RE-DERIVED here rather than patched, because its
    first step had gone false.** It used to read *"`CASTING_INK_STUDIO_SCOPE` is
    absent in production, so no design row exists, so no plate exists"*. That
    flag is `users:1`, so design rows CAN exist. What holds the conclusion up
    today is one step further along the same road: `MANNEQUIN_ROAD_DEFERRED`
    (`shared/inkMannequinDeferral.ts`) means **no upload mints a plate at all**,
    on any account, so there is no plate for this clause to be written about.
    A containment argument whose first step is false is worth repairing even
    when its answer survives — and the support it now rests on is a CONSTANT
    rather than a flag position, which is the sturdier of the two.

    The clause stays — it is the right sentence, it costs nothing per render,
    and it is what the other lane measured. It is unconditional here because the
    view clause is house prose on a new road with no installed behaviour to
    protect — `CASTING_SIDE_PHRASING_SCOPE` governs the REPAINT recipe, which is
    a different lane with a different history.

    Through the one owner rather than spelled here: a second copy of this phrase
    would drift at exactly the point it exists to hold still.
  */
  return `${input.possessive} ${input.side} ${surface}${imageHalfClause(input.side)}`;
}

/**
 * MAY A DESIGN AT THIS SURFACE RIDE A PACKAGE VIEW AT ALL — the interim ordered
 * fable-1006 §2, and the court is what bought it.
 *
 * The upper chest is bare **on a scoop neckline only** — the placement
 * vocabulary has said so since the day sixteen production masters were measured
 * — and the package wardrobe is a FIXED crew neck, unchanged across every view.
 * Those two promises cannot both hold in one frame, and the engine demonstrated
 * it by breaking each in turn: told to put the artwork on her upper chest it
 * printed the design on the shirt; told that ink goes on skin and never on
 * cloth, it rewrote the crew neck into a scoop and drew it on the skin beneath.
 *
 * **Both outcomes fail the package's own wardrobe check, and a failed view is a
 * refunded slice** — so an upper-chest design carries no plate into a package
 * view and says so on the same disposition surface as every other way a design
 * can fail to ride.
 *
 * # HE HAS NOW RULED THE WARDROBE, AND IT IS NOT WHAT LIFTS THIS
 *
 * The interim above read *"until he rules on the wardrobe itself"*, and he
 * ruled on 2026-08-19 (fable-1081 §2–§3): **the crew neck stays a crew neck**,
 * the wardrobe is never altered for a tattoo, and a covered design shows
 * whatever the collar leaves bare and nothing more. That answer closes the
 * question this interim was waiting on WITHOUT lifting the interim, which is
 * the distinction worth writing down rather than remembering — a ruling that
 * settles a question is not automatically a ruling that opens a door.
 *
 * **This read *"what lifts it is the crop road"* (fable-1081 §3) — AND THE CROP
 * ROAD HAS NOW LANDED WITHOUT LIFTING IT** (fable-1303 §2), which is the same
 * distinction one turn along and worth the correction rather than the
 * assumption. `inkViewCropClause` carries a chest design as reference plus words
 * exactly as that sentence described, and this table still says `false` for it,
 * because the reason was never the plate: a view whose wardrobe comes back
 * crew-necked has no skin to put the design on however the picture arrives, and
 * both outcomes fail the wardrobe axis and refund a slice — five times per Sign.
 *
 * ⚠ **AND THE THING THIS PARAGRAPH SAID WOULD LIFT IT IS RETIRED — THE PATH
 * DECIDES** (founder ruling 2026-08-21, relayed fable-1311; design
 * `docs/specs/CASTING_V2_TWO_PATHS_DESIGN.md`, §10 item 5). It used to read
 * *"two things lift it together and neither is code: his own word on hidden vs
 * scoop, and then a 450-credit dev Sign"* — a question he replaced rather than
 * answered. A cast is now born on the WARDROBE path or the BASICS path, and the
 * path settles where ink can go: a chest design rides when this cast's own
 * wardrobe leaves the chest bare and does not when it covers it.
 *
 * ✅ **AND THAT SITTING IS THIS ONE — THE TABLE IS GONE** (item 7a,
 * countersigned fable-1368). It is not a fact about the PLACEMENT and never
 * was: `neck: true` and `upperArm: true` were read off sixteen masters in the
 * house crew tee exactly as `upperChest: false` was, and the two `true`s are
 * the dangerous direction — `false` refuses a capability, `true` SELLS one, and
 * a neck design sold onto a roll-neck jumper rides all five views and fails the
 * wardrobe axis on every one.
 *
 * The answer now comes from `inkSurfaceCoverage.ts`, which holds the
 * measurement (quoted there in full) and applies it to the cast's OWN stored
 * line. ONE OWNER for both ink lanes, so a chest tattoo cannot ride as a crop
 * while being refused as a plate — and one owner for the gate as well, so it
 * cannot be sold and then refused.
 *
 * TOTALITY is the owner's now, and for the same reason it was this table's: a
 * default would decide a new surface's visibility by whichever value was listed
 * first, and nothing would say so.
 *
 * `CAST_PACKAGE_WARDROBE_SPEC`'s own self-contradiction — it hard-codes
 * *crew-neck* while naming the reference photograph as the authority — was
 * repaired by item 6's `castPackageWardrobeSpec(line)` and is not this
 * function's to carry.
 *
 * ⚠ **AND IT ANSWERS `bare | covered | unknown` RATHER THAN A BOOLEAN**, which
 * is ruling 1 in the signature. A `false` that cannot say whether it means *a
 * garment is over this* or *nobody has read this outfit* forces its caller to
 * pick one name for two facts, and the name it would pick is the covering — a
 * refusal that lies about why it closed. The boolean form was written first and
 * deleted before it shipped: it had no production caller (`signService` needs
 * the reason, both lanes), and an exported convenience nobody calls is a second
 * door that drifts from the first.
 */
export function placementRideCoverage(
  placement: InkPlacement,
  /**
   * The Cast's snapshotted outfit. `null` and absent are *no line recorded*,
   * which is every Cast signed before the paths, and answer the house table
   * exactly — the compatibility contract, not a default.
   */
  wardrobeLine: string | null | undefined,
): SurfaceCoverage {
  return coverageOfWardrobeLine(wardrobeLine, placement);
}

/**
 * The clause that rides beside the anchor, one sentence group per plate.
 *
 * `firstOrdinal` is the position of the FIRST plate in the request's reference
 * array — the anchor is reference 1, so plates start at 2. It is passed rather
 * than assumed, because the ordinal a sentence quotes and the slot a reference
 * actually occupies drifting apart is a prompt that points at the wrong picture.
 *
 * Empty string when nothing rides: a Cast with no plated tattoo must produce the
 * prompt it produces today, byte for byte, or every signed Cast in the product
 * has quietly changed.
 */
export function inkViewReferenceClause(input: {
  plates: readonly CarriedInkPlate[];
  firstOrdinal: number;
}): string {
  if (input.plates.length === 0) return "";
  const lines: string[] = [
    "HER TATTOOS — each of the following reference pictures shows one tattoo she already has, "
    + "drawn on a plain grey mannequin form so the artwork can be seen clearly.",
  ];
  input.plates.forEach((plate, index) => {
    /* "her", because every sentence around it says "her" — see the parameter's
       own docblock. The pronoun defect on this lane is fixed by fixing the
       lane, not by making one clause disagree with its neighbours. */
    const where = inkPlacementPhrase({ ...plate, possessive: "her" });
    lines.push(
      `Reference ${input.firstOrdinal + index} is the tattoo at ${where}. Copy the ARTWORK from it — `
      + "its shapes, its line weight, its shading and any lettering exactly as they appear — onto her "
      + `own skin at ${where}, following the form of her body so it sits as ink on skin rather than as `
      + "a flat sticker. Do not restyle it, do not simplify it, and do not add to it.",
    );
  });
  lines.push(
    "The mannequin form in those pictures is NOT part of the tattoo: its grey colour, its shape, its "
    + "background and its lighting must not appear anywhere in the photograph, and it must never "
    + "change her skin, her build or her pose.",
  );
  /*
    INK IS ON SKIN, AND A COVERED SURFACE MEANS ABSENT — the first conformance
    court's own finding (2026-08-19), and it cost a render to learn.

    Handed an upper-chest plate and a `frontFull` view whose wardrobe is a
    crew-neck tee, the engine printed the design ON THE SHIRT: the artwork
    reproduced faithfully, in the wrong material. It was the only way to satisfy
    what it had been told — the upper chest is COVERED on a crew neck, which the
    placement vocabulary states in its own table, so there was no skin in that
    frame to put it on.

    And it is a money defect rather than a cosmetic one: the package's wardrobe
    check calls printed text or a logo on the garment a failure WHEREVER it
    appears, so that view would have been refused and its slice refunded. An
    upper-chest tattoo would have cost a slice of every Sign it rode.

    # AND WHAT THE COVERED CASE LOOKS LIKE IS NOW HIS RULING, NOT A SIDE EFFECT

    Founder, 2026-08-19 (relayed fable-1081), on the same question that closed
    the scoop-neck card:

    > *"tattos can still ride they may just not be visible fully yet so if you
    > had a chest tatto reference with neck continuation you might see it poking
    > out the top of the shirt but thats the extent for now"*

    So clothing COVERS ink rather than deleting it, and the sentence below says
    so in those terms. The earlier wording — *"the tattoo is simply not visible
    in that view"* — was true of a design wholly under a collar and WRONG of the
    one he described: a chest piece that runs up the neck has a part on bare
    skin, and that part shows. The wardrobe is never altered to reveal more of
    it, and no view is added to; a poke above the collar is the whole of what a
    covered design gets, and that is the promise rather than the compromise.
  */
  lines.push(INK_NOT_ON_CLOTHING);
  lines.push(INK_VIEW_PLACEMENT_DISCIPLINE);
  return lines.join("\n");
}

/**
 * WHERE A TATTOO GOES AND WHERE IT DOES NOT — the discipline both view lanes
 * end on, spelled once.
 *
 * Two facts, and each of them is a frame this product would otherwise have to
 * refund: a tattoo copied onto the wrong arm or drawn twice, and a tattoo
 * INVENTED into a view whose framing never shows its surface. The second is the
 * cost of handing every view every picture (this module's own header), and this
 * sentence is what makes that cost safe to pay.
 */
export const INK_VIEW_PLACEMENT_DISCIPLINE =
  "Each tattoo sits where it is named and nowhere else — do not move one to a nearby part of the "
  + "body, do not mirror it to her other side, and do not draw a second copy of it. Where a view "
  + "does not show the surface a tattoo is on, that tattoo simply does not appear in that view.";

/**
 * The same fact in the CAST'S OWN PRONOUN, for the lane that has one.
 *
 * A second SHAPE of one fact and not a second fact — `inkNotOnClothingClause`'s
 * relationship to {@link INK_NOT_ON_CLOTHING}, on the sentence beside it, and
 * held the same way: `inkViewReferences.test.ts` drives both and asserts they
 * are the same words with the pronoun substituted, so neither can be edited
 * alone.
 */
export function inkViewPlacementDisciplineClause(pronouns: { possessive: string }): string {
  return INK_VIEW_PLACEMENT_DISCIPLINE.replace(
    "her other side",
    `${pronouns.possessive} other side`,
  );
}

/**
 * ONE DELIVERED CROP as a view render sees it — the tattoo as it actually
 * landed on this person, cut out of the frame that delivered it.
 *
 * # It is not a plate, and the difference is the whole lane
 *
 * A plate is artwork on a grey mannequin: a picture of the DESIGN, with no size
 * in it and nobody's skin in it. A delivered crop is a picture of HER — the ink
 * in her own skin, at the tone and the scale it really sits at, cut out on
 * transparency. That is why this lane exists (fable-1297 §3): the plate road is
 * parked, so a signed Cast's views have never once carried a tattoo, while the
 * delivery store has held real crops of real ink since migration 0049.
 *
 * `slot` travels because it is what the branch names the tattoo by, and the
 * disposition line has to be able to say which tattoo did not ride. `noun` is
 * the catalogue's — `left upper arm tattoo` — never composed here.
 */
export type CarriedInkCrop = {
  readonly cropPublicId: string;
  readonly slot: string;
  readonly placement: InkPlacement;
  readonly side: InkSide;
  readonly noun: string;
  readonly bytes: Buffer;
  readonly contentType: string;
};

/**
 * The clause that rides beside the anchor for DELIVERED crops, one sentence
 * group per crop.
 *
 * # The sentence is the transform road's, and it is not re-written here
 *
 * `inkDeliveredCarrySentence` is the one owner of *what this picture is* — that
 * it is cut from a photograph of her, that the skin in it is her own, that the
 * transparent area is not the instruction, and that whatever edge is visible is
 * the real edge of the design. Three clauses were said to that lane before this
 * one landed and all three put a design a third of the way down a white
 * T-shirt; a second spelling here would lose that measurement silently, on a
 * frame somebody paid for.
 *
 * **The mannequin sentence must never be said about a crop.** The plate lane
 * ends by disclaiming the grey form — its colour, its background, its lighting
 * — and every word of that would be a lie about this picture: there is no
 * mannequin in it, and the skin in it is the very fact being supplied.
 *
 * # And WHERE, because a crop cannot picture its own side
 *
 * A plate holds the side it pictures (the mirror court, above). A delivered crop
 * is the design alone on transparency, so the arm it came off is not IN the
 * picture and prose is the only thing that can carry it. It goes through
 * `inkPlacementPhrase` — the one owner of which half of the frame a side is —
 * rather than a second spelling of that clause.
 *
 * `firstOrdinal` is the position of the FIRST crop in the request's reference
 * array, derived by the caller from the array it is quoting about.
 *
 * Empty string when nothing rides: a Cast with no delivered tattoo must produce
 * the prompt it produces today, byte for byte.
 */
export function inkViewCropClause(input: {
  crops: readonly CarriedInkCrop[];
  firstOrdinal: number;
  pronouns: CastPronouns;
}): string {
  if (input.crops.length === 0) return "";
  const { pronouns } = input;
  const has = pronouns.plural ? "have" : "has";
  const lines: string[] = [
    `${pronouns.possessive.toUpperCase()} TATTOOS — each of the reference pictures below is one `
    + `tattoo ${pronouns.subject} already ${has}, cut out of a photograph of ${pronouns.object}.`,
  ];
  input.crops.forEach((crop, index) => {
    const where = inkPlacementPhrase({
      placement: crop.placement,
      side: crop.side,
      possessive: pronouns.possessive,
    });
    lines.push(
      `${inkDeliveredCarrySentence(input.firstOrdinal + index, crop.noun, pronouns)}`
      + ` It is on ${where}: draw it there and nowhere else.`,
    );
  });
  lines.push(inkViewPlacementDisciplineClause(pronouns));
  return lines.join("\n");
}
